# -*- coding: utf-8 -*-
"""python_section_2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XjWkdIjs-msxPrKY5ppGaiIG0_98m9V3
"""

import pandas as pd

# Define the file path first
file_path = 'https://raw.githubusercontent.com/mapup/MapUp-DA-Assessment-2024/refs/heads/main/datasets/dataset-2.csv'

# Now read the CSV file
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame to verify it's loaded correctly
print(df.head())

"""Question No.9"""

import pandas as pd

def calculate_distance_matrix(file_path):
    df = pd.read_csv(file_path)

    unique_ids = pd.concat([df['id_start'], df['id_end']]).unique()

    distance_matrix = pd.DataFrame(index=unique_ids, columns=unique_ids)

    for _, row in df.iterrows():
        from_id = row['id_start']
        to_id = row['id_end']
        distance = row['distance']

        distance_matrix.at[from_id, to_id] = distance
        distance_matrix.at[to_id, from_id] = distance

    for id in unique_ids:
        distance_matrix.at[id, id] = 0

    for i in range(len(unique_ids)):
        for j in range(len(unique_ids)):
            if pd.isna(distance_matrix.iat[i, j]):
                for k in range(len(unique_ids)):
                    if not pd.isna(distance_matrix.iat[i, k]) and not pd.isna(distance_matrix.iat[k, j]):
                        distance_matrix.iat[i, j] = distance_matrix.iat[i, k] + distance_matrix.iat[k, j]
                        distance_matrix.iat[j, i] = distance_matrix.iat[i, j]
                        break

    return distance_matrix

file_path = 'https://raw.githubusercontent.com/mapup/MapUp-DA-Assessment-2024/refs/heads/main/datasets/dataset-2.csv'
distance_matrix_df = calculate_distance_matrix(file_path)

print(distance_matrix_df)

"""Question No.12"""

import pandas as pd

def calculate_toll_rate(unrolled_df):
    rate_coefficients = {
        'moto': 0.8,
        'car': 1.2,
        'rv': 1.5,
        'bus': 2.2,
        'truck': 3.6
    }

    for vehicle_type, rate in rate_coefficients.items():
        unrolled_df[vehicle_type] = unrolled_df['distance'] * rate

    return unrolled_df

# Assuming unrolled_df is the DataFrame from the previous function
toll_rate_df = calculate_toll_rate(unrolled_df)

print(toll_rate_df)

"""Question No.13"""

import pandas as pd
import datetime

def calculate_time_based_toll_rates(unrolled_df):
    weekday_discounts = {
        'morning': 0.8,  # From 00:00 to 10:00
        'daytime': 1.2,  # From 10:00 to 18:00
        'evening': 0.8   # From 18:00 to 23:59
    }
    weekend_discount = 0.7

    # Define the days of the week
    days_of_week = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

    # Create time ranges for weekdays
    morning_start = datetime.time(0, 0, 0)
    morning_end = datetime.time(10, 0, 0)
    daytime_start = datetime.time(10, 0, 0)
    daytime_end = datetime.time(18, 0, 0)
    evening_start = datetime.time(18, 0, 0)
    evening_end = datetime.time(23, 59, 59)

    unrolled_df['start_day'] = days_of_week[0]
    unrolled_df['end_day'] = days_of_week[-1]
    unrolled_df['start_time'] = morning_start
    unrolled_df['end_time'] = evening_end

    for vehicle_type in ['moto', 'car', 'rv', 'bus', 'truck']:
        adjusted_rates = []

        for _, row in unrolled_df.iterrows():
            start_day = row['start_day']
            start_time = row['start_time']
            distance = row[vehicle_type]

            # Determine the discount factor
            if start_day in ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday']:
                # Weekday
                if morning_start <= start_time < morning_end:
                    discount = weekday_discounts['morning']
                elif daytime_start <= start_time < daytime_end:
                    discount = weekday_discounts['daytime']
                else:
                    discount = weekday_discounts['evening']
            else:
                # Weekend
                discount = weekend_discount

            adjusted_rate = distance * discount
            adjusted_rates.append(adjusted_rate)

        unrolled_df[vehicle_type] = adjusted_rates

    return unrolled_df


time_based_toll_df = calculate_time_based_toll_rates(unrolled_df)

print(time_based_toll_df)

"""Question No.10"""

import pandas as pd

def unroll_distance_matrix(distance_matrix):
    id_start = []
    id_end = []
    distances = []

    for i in range(len(distance_matrix)):
        for j in range(len(distance_matrix)):
            start_id = distance_matrix.index[i]
            end_id = distance_matrix.columns[j]
            distance = distance_matrix.iat[i, j]

            if start_id != end_id and not pd.isna(distance):
                id_start.append(start_id)
                id_end.append(end_id)
                distances.append(distance)

    unrolled_df = pd.DataFrame({
        'id_start': id_start,
        'id_end': id_end,
        'distance': distances
    })

    return unrolled_df

distance_matrix_df = calculate_distance_matrix(file_path)
unrolled_df = unroll_distance_matrix(distance_matrix_df)

print(unrolled_df)

"""Question No.11"""

import pandas as pd
import numpy as np

def find_ids_within_ten_percentage_threshold(unrolled_df, reference_id):
    filtered_df = unrolled_df[unrolled_df['id_start'] == reference_id]

    if filtered_df.empty:
        return []

    average_distance = filtered_df['distance'].mean()

    lower_bound = average_distance * 0.90
    upper_bound = average_distance * 1.10

    ids_within_threshold = unrolled_df[
        (unrolled_df['distance'] >= lower_bound) &
        (unrolled_df['distance'] <= upper_bound)
    ]['id_start'].unique()

    sorted_ids = sorted(ids_within_threshold)

    return sorted_ids


# Assuming unrolled_df is the DataFrame from the previous function
reference_id = 1001400
resulting_ids = find_ids_within_ten_percentage_threshold(unrolled_df, reference_id)

print(resulting_ids)

"""<div class="markdown-google-sans">
  <h2>What is Colab?</h2>
</div>

Colab, or "Colaboratory", allows you to write and execute Python in your browser, with
- Zero configuration required
- Access to GPUs free of charge
- Easy sharing

Whether you're a **student**, a **data scientist** or an **AI researcher**, Colab can make your work easier. Watch [Introduction to Colab](https://www.youtube.com/watch?v=inN8seMm7UI) or [Colab Features You May Have Missed](https://www.youtube.com/watch?v=rNgswRZ2C1Y) to learn more, or just get started below!

<div class="markdown-google-sans">

## **Getting started**
</div>

The document you are reading is not a static web page, but an interactive environment called a **Colab notebook** that lets you write and execute code.

For example, here is a **code cell** with a short Python script that computes a value, stores it in a variable, and prints the result:
"""

seconds_in_a_day = 24 * 60 * 60
seconds_in_a_day

"""To execute the code in the above cell, select it with a click and then either press the play button to the left of the code, or use the keyboard shortcut "Command/Ctrl+Enter". To edit the code, just click the cell and start editing.

Variables that you define in one cell can later be used in other cells:
"""

seconds_in_a_week = 7 * seconds_in_a_day
seconds_in_a_week

"""Colab notebooks allow you to combine **executable code** and **rich text** in a single document, along with **images**, **HTML**, **LaTeX** and more. When you create your own Colab notebooks, they are stored in your Google Drive account. You can easily share your Colab notebooks with co-workers or friends, allowing them to comment on your notebooks or even edit them. To learn more, see [Overview of Colab](/notebooks/basic_features_overview.ipynb). To create a new Colab notebook you can use the File menu above, or use the following link: [create a new Colab notebook](http://colab.research.google.com#create=true).

Colab notebooks are Jupyter notebooks that are hosted by Colab. To learn more about the Jupyter project, see [jupyter.org](https://www.jupyter.org).

<div class="markdown-google-sans">

## Data science
</div>

With Colab you can harness the full power of popular Python libraries to analyze and visualize data. The code cell below uses **numpy** to generate some random data, and uses **matplotlib** to visualize it. To edit the code, just click the cell and start editing.

You can import your own data into Colab notebooks from your Google Drive account, including from spreadsheets, as well as from Github and many other sources. To learn more about importing data, and how Colab can be used for data science, see the links below under [Working with Data](#working-with-data).
"""

import numpy as np
import IPython.display as display
from matplotlib import pyplot as plt
import io
import base64

ys = 200 + np.random.randn(100)
x = [x for x in range(len(ys))]

fig = plt.figure(figsize=(4, 3), facecolor='w')
plt.plot(x, ys, '-')
plt.fill_between(x, ys, 195, where=(ys > 195), facecolor='g', alpha=0.6)
plt.title("Sample Visualization", fontsize=10)

data = io.BytesIO()
plt.savefig(data)
image = F"data:image/png;base64,{base64.b64encode(data.getvalue()).decode()}"
alt = "Sample Visualization"
display.display(display.Markdown(F"""![{alt}]({image})"""))
plt.close(fig)

"""Colab notebooks execute code on Google's cloud servers, meaning you can leverage the power of Google hardware, including [GPUs and TPUs](#using-accelerated-hardware), regardless of the power of your machine. All you need is a browser.

For example, if you find yourself waiting for **pandas** code to finish running and want to go faster, you can switch to a GPU Runtime and use libraries like [RAPIDS cuDF](https://rapids.ai/cudf-pandas) that provide zero-code-change acceleration.

To learn more about accelerating pandas on Colab, see the [10 minute guide](https://colab.research.google.com/github/rapidsai-community/showcase/blob/main/getting_started_tutorials/cudf_pandas_colab_demo.ipynb) or
 [US stock market data analysis demo](https://colab.research.google.com/github/rapidsai-community/showcase/blob/main/getting_started_tutorials/cudf_pandas_stocks_demo.ipynb).

<div class="markdown-google-sans">

## Machine learning
</div>

With Colab you can import an image dataset, train an image classifier on it, and evaluate the model, all in just [a few lines of code](https://colab.research.google.com/github/tensorflow/docs/blob/master/site/en/tutorials/quickstart/beginner.ipynb).

Colab is used extensively in the machine learning community with applications including:
- Getting started with TensorFlow
- Developing and training neural networks
- Experimenting with TPUs
- Disseminating AI research
- Creating tutorials

To see sample Colab notebooks that demonstrate machine learning applications, see the [machine learning examples](#machine-learning-examples) below.

<div class="markdown-google-sans">

## More Resources

### Working with Notebooks in Colab

</div>

- [Overview of Colab](/notebooks/basic_features_overview.ipynb)
- [Guide to Markdown](/notebooks/markdown_guide.ipynb)
- [Importing libraries and installing dependencies](/notebooks/snippets/importing_libraries.ipynb)
- [Saving and loading notebooks in GitHub](https://colab.research.google.com/github/googlecolab/colabtools/blob/main/notebooks/colab-github-demo.ipynb)
- [Interactive forms](/notebooks/forms.ipynb)
- [Interactive widgets](/notebooks/widgets.ipynb)

<div class="markdown-google-sans">

<a name="working-with-data"></a>
### Working with Data
</div>

- [Loading data: Drive, Sheets, and Google Cloud Storage](/notebooks/io.ipynb)
- [Charts: visualizing data](/notebooks/charts.ipynb)
- [Getting started with BigQuery](/notebooks/bigquery.ipynb)

<div class="markdown-google-sans">

### Machine Learning Crash Course

<div>

These are a few of the notebooks from Google's online Machine Learning course. See the [full course website](https://developers.google.com/machine-learning/crash-course/) for more.
- [Intro to Pandas DataFrame](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/pandas_dataframe_ultraquick_tutorial.ipynb)
- [Intro to RAPIDS cuDF to accelerate pandas](https://nvda.ws/rapids-cudf)
- [Linear regression with tf.keras using synthetic data](https://colab.research.google.com/github/google/eng-edu/blob/main/ml/cc/exercises/linear_regression_with_synthetic_data.ipynb)

<div class="markdown-google-sans">

<a name="using-accelerated-hardware"></a>
### Using Accelerated Hardware
</div>

- [TensorFlow with GPUs](/notebooks/gpu.ipynb)
- [TensorFlow with TPUs](/notebooks/tpu.ipynb)

<div class="markdown-google-sans">

<a name="machine-learning-examples"></a>

### Featured examples

</div>

- [Retraining an Image Classifier](https://tensorflow.org/hub/tutorials/tf2_image_retraining): Build a Keras model on top of a pre-trained image classifier to distinguish flowers.
- [Text Classification](https://tensorflow.org/hub/tutorials/tf2_text_classification): Classify IMDB movie reviews as either *positive* or *negative*.
- [Style Transfer](https://tensorflow.org/hub/tutorials/tf2_arbitrary_image_stylization): Use deep learning to transfer style between images.
- [Multilingual Universal Sentence Encoder Q&A](https://tensorflow.org/hub/tutorials/retrieval_with_tf_hub_universal_encoder_qa): Use a machine learning model to answer questions from the SQuAD dataset.
- [Video Interpolation](https://tensorflow.org/hub/tutorials/tweening_conv3d): Predict what happened in a video between the first and the last frame.
"""